# Module: ErpBancosOficinas
# Document : modules/ErpBancosOficinas/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 01.04.2013 16:52:30
#
---
BancosOficinas:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDBanco
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDBanco
  controller: BancosOficinas
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Oficinas Bancarias
  id_video: bancosoficinas
  url_video: null
  feature_list: true
  conection: ''
  entity: BancosOficinas
  table: ErpBancosOficinas
  primarykey: ID
  linkBy: IDBanco
  records_per_page: 10
  order_by:
    -
      title: 'Dirección a-z'
      criteria: 'Direccion ASC'
    -
      title: 'Dirección z-a'
      criteria: 'Direccion DESC'
  search_default: Direccion
  referenced_entities:
    - Bancos
    - Paises
    - Provincias
    - Municipios
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    ID:
      title: ID
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDBanco:
      title: Banco
      filter: false
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: Banco, entity: Bancos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDOficina:
      title: Oficina
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '4', min: null, max: null, message: 'Valor Requerido' }
    Digito:
      title: Dígito
      filter: false
      list: false
      visible: true
      updatable: true
      default: 0
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 2, caption: Dígito, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    Direccion:
      title: Dirección
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    IDPais:
      title: País
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 3, caption: País, entity: Paises, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDProvincia:
      title: Provincia
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 4, caption: Provincia, entity: Provincias, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDPoblacion:
      title: Población
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 5, caption: Población, entity: Municipios, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    CodigoPostal:
      title: Código Postal
      filter: true
      list: false
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Fax:
      title: Fax
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
