# Module: Facturacion
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Facturacion:
  login_required: true
  permission_control: true
  help_file: help.html.twig
  title: Facturación
  conection: ''
  entity: AlbaranesCab
  table: albaranes_cab
  primarykey: IDAlbaran
  records_per_page: 20
  order_by: Fecha
  search_default: IDAlbaran