# Module: Municipios
# Document : modules/Municipios/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 02.02.2014 01:19:34
#
---
Municipios:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDPais
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDPais
  fieldGeneratorMetatagDescription: IDPais
  fieldGeneratorMetatagKeywords: IDPais
  controller: Municipios
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: true
  permission_control: true
  favourite_control: NO
  help_file: help.html.twig
  title: Municipios
  id_video: municipios
  url_video: null
  feature_list: true
  conection: ''
  entity: Municipios
  table: ErpMunicipios
  primarykey: IDMunicipio
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'Municipio a-z'
      criteria: 'IDPais ASC,IDProvincia ASC,Municipio ASC'
    -
      title: 'Municipio z-a'
      criteria: 'IDPais ASC,IDProvincia ASC,Municipio DESC'
  search_default: Municipio
  referenced_entities:
    - Paises
    - Provincias
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDMunicipio:
      title: IDMunicipio
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDPais:
      title: País
      filter: false
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: País, entity: Paises, method: fetchAll, params: Pais, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDProvincia:
      title: Provincia
      filter: false
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 2, caption: Provincia, entity: Provincias, method: fetchAll, params: Provincia, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Codigo:
      title: Código
      filter: false
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '5', min: null, max: null, message: 'Valor Requerido' }
    DigitoControl:
      title: Dígito Control
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '2', min: null, max: null, message: 'Valor Requerido' }
    Municipio:
      title: Municipio
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '2555', min: null, max: null, message: 'Valor Requerido' }
