# Module: Listas
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Listas:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Listas
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Listas
  table: listas
  primarykey: IDLista
  records_per_page: 10
  order_by: IDLista
  search_default: IDLista
  columns:
    - 
      title: IDLista
      field: IDLista
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: Descripcion
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Vigencia
      field: Vigencia
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Periodicidad
      field: Periodicidad
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: YES
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: UltimoEnvio
      field: UltimoEnvio
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: ProximoEnvio
      field: ProximoEnvio
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Tabla
      field: Tabla
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Condiciones
      field: Condiciones
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Columnas
      field: Columnas
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: null
        min: null
        max: null
        message: Valor Requerido
