# Module: Submenu
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Submenu:
  login_required: true
  permission_control: true
  help_file: help.html.twig
  title: Submenu
  conection: empresas
  entity: Submenu
  table: submenu
  primarykey: Id
  linkBy: IDOpcion
  records_per_page: 9999
  order_by: Orden
  search_default: Titulo
  columns:
    - 
      title: Id
      field: Id
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: IDOpcion
      field: IDOpcion
      filter: true
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Script
      field: Script
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Titulo
      field: Titulo
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Orden
      field: Orden
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Administrador
      field: Administrador
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Emergente
      field: Emergente
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
