# Module: BlogComentarios
# Document : modules/BlogComentarios/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: INFORMATICA ALBATRONIC SL
# @date 21.02.2013 21:32:01
#
---
BlogComentarios:
  app: 'Blog'
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: true
  searchable: true  
  showCommonFields: true
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Entidad
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Entidad
  controller: BlogComentarios
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Comentarios del Blog
  id_video: blogcomentarios
  url_video: null
  feature_list: true
  conection: ''
  entity: BlogComentarios
  table: BlogComentarios
  primarykey: Id
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'Fecha z-a'
      criteria: 'TiempoUnix DESC'    
    -
      title: 'Fecha a-z'
      criteria: 'TiempoUnix ASC'
  search_default: Id
  referenced_entities:
    - GconContenidos
    - CpanUsuarios
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
    Entidad:
      title: Tipo Entidad
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: Tipo entidad, entity: BlogComentarios, method: fetchAllAditional, params: Entidad, type: select, operator: '=', event: null }      
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    IdEntidad:
      title: Entidad
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 1, caption: IdEntidad, entity: GconContenidos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IpAddress:
      title: Dirección IP
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '15', min: null, max: null, message: 'Valor Requerido' }
    IdUsuario:
      title: Usuario
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 2, caption: IdUsuario, entity: CpanUsuarios, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Nombre:
      title: Nombre
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Email:
      title: Email
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    TiempoUnix:
      title: Fecha
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '20', min: null, max: null, message: 'Valor Requerido' }
    Comentario:
      title: Comentario
      filter: true
      list: false
      visible: true
      updatable: true
      searchable: true      
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: false, min: null, max: null, message: 'Valor Requerido' }
    Checked:
      title: Aprobar
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 3, caption: Aprobar, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    Publish:
      title: Publicar
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 4, caption: Publicar, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }      