# Module: Paises
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Paises:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Pais
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Pais
  controller: Paises
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Paises
  id_video: paises
  url_video: null
  feature_list: YES
  conection: ''
  entity: Paises
  table: ErpPaises
  primarykey: IDPais
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: País a-z
      criteria: Pais ASC
    -
      title: País z-a
      criteria: Pais DESC
  search_default: Pais  
  columns:
    IDPais: 
      title: IDPais
      filter: NO
      list: NO
      visible: false
      updatable: false
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    Codigo: 
      title: Código
      filter: YES
      list: YES
      visible: true
      updatable: true      
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: YES
        type: integer
        length: 6
        min: null
        max: null
        message: Valor Requerido
    Pais: 
      title: País
      filter: YES
      list: YES
      visible: true
      updatable: true        
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: YES
        type: null
        length: 30
        min: null
        max: null
        message: Valor Requerido
    IDMoneda: 
      title: Moneda
      filter: NO
      list: YES
      visible: true
      updatable: true        
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: YES
        type: null
        length: 15
        min: null
        max: null
        message: Valor Requerido
      aditional_filter: { order: 1, caption: Moneda, entity: Monedas, method: fetchAll, params: Moneda, type: select, operator: '=', event: null }        
    IDZonaHoraria: 
      title: Zona Horaria
      filter: NO
      list: YES
      visible: true
      updatable: true        
      default: null
      validator:
        nullable: NO
        type: string
        length: 30
        min: null
        max: null
        message: Valor Requerido
      aditional_filter: { order: 2, caption: Zona Horaria, entity: ZonasHorarias, method: fetchAll, params: Zona, type: select, operator: '=', event: null }        
    Latitud: 
      title: Latitud
      filter: NO
      list: YES
      visible: true
      updatable: true        
      default: null
      validator:
        nullable: NO
        type: string
        length: 7
        min: null
        max: null
        message: Valor Requerido        
    Longitud: 
      title: Longitud
      filter: NO
      list: YES
      visible: true
      updatable: true        
      default: null
      validator:
        nullable: NO
        type: string
        length: 7
        min: null
        max: null
        message: Valor Requerido          
