# Module: AvisadorStock
# Document : modules/AvisadorStock/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 19.07.2014 02:26:08
#
---
AvisadorStock:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDCliente
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDCliente
  fieldGeneratorMetatagDescription: IDCliente
  fieldGeneratorMetatagKeywords: IDCliente
  controller: AvisadorStock
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Avisador de Stock
  id_video: avisadorstock
  url_video: null
  feature_list: YES
  conection: ''
  entity: AvisadorStock
  table: ErpAvisadorStock
  primarykey: Id
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'Id a-z'
      criteria: 'Id ASC'
    -
      title: 'Id z-a'
      criteria: 'Id DESC'
  search_default: Id
  referenced_entities:
    - Clientes
    - Articulos
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDCliente:
      title: Cliente
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 1, caption: IDCliente, entity: Clientes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Email:
      title: Email
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    IDArticulo:
      title: Articulo
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 2, caption: Articulo, entity: Articulos, method: fetchAll, params: Descripcion, type: input, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '45', min: null, max: null, message: 'Valor Requerido' }
    CreatedAt:
      title: Fecha Petición
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    EmailedAt:
      title: Notificado el
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }