# Module: Menu
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Menu:
  login_required: true
  permission_control: true
  help_file: help.html.twig
  title: Menu
  conection: empresas
  entity: Menu
  table: menu
  primarykey: IDOpcion
  records_per_page: 10
  order_by:
    -
      title: Orden a-z
      criteria: Orden ASC
    -
      title: Orden z-a
      criteria: Orden DESC
  search_default: IDOpcion
  columns:
    - 
      title: IDOpcion
      field: IDOpcion
      filter: false
      list: false
      form: true
      default: null
    - 
      title: Script
      field: Script
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Titulo
      field: Titulo
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Orden
      field: Orden
      filter: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Administrador
      field: Administrador
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Icono
      field: Icono
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
