# Module: ErpRutasReparto
# Document : modules/ErpRutasReparto/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:29
#
---
RutasReparto:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDSucursal
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDSucursal
  controller: RutasReparto
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: NO
  help_file: help.html.twig
  title: Rutas de Reparto
  id_video: rutasreparto
  url_video: null
  feature_list: true
  conection: ''
  entity: RutasReparto
  table: ErpRutasReparto
  primarykey: IDRuta
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'IDRuta a-z'
      criteria: 'IDRuta ASC'
    -
      title: 'IDRuta z-a'
      criteria: 'IDRuta DESC'
  search_default: IDRuta
  referenced_entities:
    - Sucursales
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDRuta:
      title: IDRuta
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDSucursal:
      title: Sucursal
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: Sucursal, entity: Sucursales, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Descripcion:
      title: Descripción
      filter: true
      list: true
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }

