# Module: Afiliados
# Document : modules/Afiliados/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 13.07.2014 17:39:52
#
---
Afiliados:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: RazonSocial
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: RazonSocial
  fieldGeneratorMetatagDescription: RazonSocial
  fieldGeneratorMetatagKeywords: RazonSocial
  controller: Afiliados
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Afiliados
  id_video: afiliados
  url_video: null
  feature_list: true
  conection: ''
  entity: Afiliados
  table: ErpAfiliados
  primarykey: IDAfiliado
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'Razón Social a-z'
      criteria: 'RazonSocial ASC'
    -
      title: 'Razón Social z-a'
      criteria: 'RazonSocial DESC'
    -
      title: 'Antiguedad a-z'
      criteria: 'CreatedAt ASC'
    -
      title: 'Antiguedad z-a'
      criteria: 'CreatedAt DESC'      
  search_default: RazonSocial
  referenced_entities:
    - Paises
    - Provincias
    - Municipios
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDAfiliado:
      title: IDAfiliado
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    RazonSocial:
      title: Razón Social
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    NombreComercial:
      title: Nombre Comercial
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    Cif:
      title: Cif
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '15', min: null, max: null, message: 'Valor Requerido' }
    Direccion:
      title: Dirección
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    IDPais:
      title: Pais
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 1, caption: Pais, entity: Paises, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDProvincia:
      title: Provincia
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 2, caption: Provincia, entity: Provincias, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDPoblacion:
      title: Población
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 3, caption: Poblacion, entity: Municipios, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    CodigoPostal:
      title: Código Postal
      filter: true
      list: false
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Fax:
      title: Fax
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Movil:
      title: Móvil
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Web:
      title: Web
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Comision:
      title: Comisión
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Iban:
      title: Iban
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '34', min: null, max: null, message: 'Valor Requerido' }
    Bic:
      title: Bic
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Mandato:
      title: Mandato
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '35', min: null, max: null, message: 'Valor Requerido' }
    FechaMandato:
      title: Fecha Mandato
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0000-00-00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 4, caption: Fecha Mandato, type: range, operator: '>=' }
      validator: { nullable: false, type: date, length: 10, min: null, max: null, message: 'Valor Requerido' }
