# Module: Agencias
# Document : modules/CpanUrlAmigables/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:23
#
---
CpanUrlAmigables:
  app: Cpan
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: UrlFriendly
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: UrlFriendly
  controller: 
  action: 
  template: 
  parametros: 
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: 'Urls Amigables'
  id_video: cpanurlamigables
  url_video: null
  feature_list: YES
  conection: ''
  entity: CpanUrlAmigables
  table: CpanUrlAmigables
  primarykey: Id
  linkBy: ''
  records_per_page: 20
  order_by:
    -
      title: 'Url amigable a-z'
      criteria: 'UrlFriendly ASC'
    -
      title: 'Url amigable z-a'
      criteria: 'UrlFriendly DESC'
    -
      title: 'Controlador a-z'
      criteria: 'Controller ASC'
    -
      title: 'Controlador z-a'
      criteria: 'Controller DESC'
  search_default: UrlFriendly
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
    Idioma:
      title: Idioma
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: 3, min: null, max: null, message: 'Valor Requerido' }
    UrlFriendly:
      title: 'Url Amigable'
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Controller:
      title: Controlador
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Action:
      title: Accion
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Template:
      title: Template
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Parameters:
      title: Parámetros
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Entity:
      title: Entidad
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    IdEntity:
      title: 'Id Entidad'
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Observations:
      title: Observations
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: false, min: null, max: null, message: 'Valor Requerido' }
    PrimaryKeyMD5:
      title: PrimaryKeyMD5
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    IsDefault:
      title: IsDefault
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    Checked:
      title: Checked
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    Publish:
      title: Publish
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    BelongsTo:
      title: BelongsTo
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    CreatedBy:
      title: CreatedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    CreatedAt:
      title: CreatedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    ModifiedBy:
      title: ModifiedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    ModifiedAt:
      title: ModifiedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    Deleted:
      title: Deleted
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    DeletedBy:
      title: DeletedBy
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
    DeletedAt:
      title: DeletedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    Privacy:
      title: Privacidad
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '10', min: null, max: null, message: 'Valor Requerido' }
      aditional_filter: { order: 1, caption: Privacidad , entity: ValoresPrivacy, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }      
    SortOrder:
      title: SortOrder
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    PublishedAt:
      title: PublishedAt
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    ActiveFrom:
      title: ActiveFrom
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    ActiveTo:
      title: ActiveTo
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0000-00-00 00:00:00'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: datetime, length: false, min: null, max: null, message: 'Valor Requerido' }
    UrlPrefix:
      title: UrlPrefix
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    LockUrlPrefix:
      title: LockUrlPrefix
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    Slug:
      title: Slug
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    LockSlug:
      title: LockSlug
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    UrlHeritable:
      title: UrlHeritable
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    NumberVisits:
      title: NumberVisits
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    MetatagTitle:
      title: MetatagTitle
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    LockMetatagTitle:
      title: LockMetatagTitle
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    MetatagKeywords:
      title: MetatagKeywords
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    MetatagDescription:
      title: MetatagDescription
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    MetatagTitleSimple:
      title: MetatagTitleSimple
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    MetatagTitlePosition:
      title: MetatagTitlePosition
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    ShowOnSitemap:
      title: ShowOnSitemap
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    ImportanceSitemap:
      title: ImportanceSitemap
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0,5'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '5', min: null, max: null, message: 'Valor Requerido' }
    ChangeFreqSitemap:
      title: ChangeFreqSitemap
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: monthly
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '25', min: null, max: null, message: 'Valor Requerido' }
    RevisitAfter:
      title: RevisitAfter
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: ''
    AccessProfileListWeb:
      title: 'Perfiles Web'
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: "perfiles:\n  - 1\n"
