# Module: Escaparates
# Document : modules/Escaparates/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 07.02.2013 15:32:56
#
---
Escaparates:
  app: 'Cpan'
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '0'
    maxHeightImage: '0'
    generateThumbnail: '0'
    widthThumbnail: '0'
    heightThumbnail: '0'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Controller
  metatagTitleManagement: true
  fieldGeneratorMetatagTitle: Controller
  controller: Escaparates
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Escaparates Web
  id_video: escaparetes
  url_video: null
  feature_list: true
  conection: ''
  entity: Escaparates
  table: Escaparates
  primarykey: Id
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'Id a-z'
      criteria: 'Id ASC'
    -
      title: 'Id z-a'
      criteria: 'Id DESC'
  search_default: Id
  referenced_entities:
    - ErpArticulosEstados
    - ErpFamilias
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
    Controller:
      title: Controller
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Zona:
      title: Zona
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '2', min: null, max: null, message: 'Valor Requerido' }
    IDLote:
      title: Lote
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: Lote, entity: LotesWeb, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }      
    IDEstado:
      title: Estado
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDEstado, entity: ArticulosEstados, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDFabricante:
      title: IDFabricante
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDFabricante, entity: ErpMarcas, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDCategoria:
      title: IDCategoria
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 2, caption: IDCategoria, entity: ErpFamilias, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDFamilia:
      title: IDFamilia
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 3, caption: IDFamilia, entity: ErpFamilias, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDSubfamilia:
      title: IDSubfamilia
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 4, caption: IDSubfamilia, entity: ErpFamilias, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Filtro:
      title: Filtro
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    NItems:
      title: NItems
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '2', min: null, max: null, message: 'Valor Requerido' }    
    ItemsPagina:
      title: Items por Página
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '2', min: null, max: null, message: 'Valor Requerido' }      