# Module: ErpFabricantes
# Document : modules/ErpFabricantes/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:26
#
---
Fabricantes:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: true
  showCommonFields: true
  withMetadata: false  
  addMetadata: false  
  deleteMetadata: false     
  numMaxRecords: ''
  numberOfImages: '1'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: true
  fieldGeneratorUrlFriendly: Titulo
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Titulo
  controller: Fabricantes
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Marcas/Fabricantes
  id_video: fabricantes
  url_video: null
  feature_list: true
  conection: ''
  entity: Fabricantes
  table: ErpFabricantes
  primarykey: IDFabricante
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'Título a-z'
      criteria: 'Titulo ASC'
    -
      title: 'Título z-a'
      criteria: 'Titulo DESC'
    -
      title: 'Orden a-z'
      criteria: 'SortOrder ASC'    
    -
      title: 'Orden Portada a-z'
      criteria: 'OrdenPortada ASC'  
  ordenes_web:
    MostrarPortada:
      columnaMostrar: Titulo
      filtro: 'MostrarPortada=''1'' and Publish=''1'''
      columnaOrden: OrdenPortada        
  search_default: Titulo
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDFabricante:
      title: IDFabricante
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Titulo:
      title: Título
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Descripcion1:
      title: Descripción1
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Descripcion2:
      title: Descripción2
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Web:
      title: Web
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    Email:
      title: Email
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    MostrarPortada:
      title: Mostrar en Portada
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: 'Mostrar en Portada', entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }            