# Module: ArticulosEstados
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
ArticulosEstados:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Estados de Artículos
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: ArticulosEstados
  table: articulos_estados
  primarykey: IDEstado
  records_per_page: 15
  order_by:
    -
      title: Estado a-z
      criteria: Estado ASC
    -
      title: Estado z-a
      criteria: Estado DESC
  search_default: IDEstado
  columns:
    - 
      title: IDEstado
      field: IDEstado
      filter: NO
      list: YES
      form: YES
      validator: null
    - 
      title: Estado
      field: Estado
      filter: YES
      list: YES
      form: YES
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
