# Module: ZonasTransporte
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
ZonasTransporte:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Zonas de Transporte
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: ZonasTransporte
  table: zonas_transporte
  primarykey: IDZona
  records_per_page: 10
  order_by:
    -
      title: Zona a-z
      criteria: Zona ASC
    -
      title: Zona z-a
      criteria: Zona DESC
  search_default: Zona
  columns:
    -
      title: Codigo
      field: IDZona
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    -
      title: Zona
      field: Zona
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
