# Module: TraspasosLineas
# Document : modules\TraspasosLineas\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 23.03.2012 19:13:09
#
---
TraspasosLineas:
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: TraspasosLineas
  id_video: traspasoslineas
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: TraspasosLineas
  table: traspasos_lineas
  primarykey: IDLinea
  records_per_page: 15
  order_by: IDLinea
  search_default: IDLinea
  referenced_entities:
    -
      entity: TraspasosCab
    -
      entity: Articulos
    -
      entity: Almacenes
    -
      entity: AlmacenesMapas
    -
      entity: EstadosTraspasos
  columns:
    -
      title: IDLinea
      field: IDLinea
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: IDTraspaso
      field: IDTraspaso
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 1
        caption: IDTraspaso
        entity: ManufacCab
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Tipo
      field: Tipo
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 2
        caption: Tipo
        entity: ValoresSN
        method: fetchAll
        params: null
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDArticulo
      field: IDArticulo
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 3
        caption: IDArticulo
        entity: Articulos
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descripcion
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: Unidades
      field: Unidades
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: UnidadMedida
      field: UnidadMedida
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: NO
        type: string
        length: 3
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDAlmacen
      field: IDAlmacen
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 4
        caption: IDAlmacen
        entity: Almacenes
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    -
      title: Precio
      field: Precio
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Importe
      field: Importe
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDEstado
      field: IDEstado
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 7
        caption: IDEstado
        entity: EstadosManufac
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
