# Module: WebPerfiles
# Document : modules/WebPerfiles/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 18.03.2014 18:36:33
#
---
WebPerfiles:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Perfil
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Perfil
  fieldGeneratorMetatagDescription: Perfil
  fieldGeneratorMetatagKeywords: Perfil
  controller: WebPerfiles
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Perfiles de los usuarios Web
  id_video: webperfiles
  url_video: null
  feature_list: YES
  conection: ''
  entity: WebPerfiles
  table: WebPerfiles
  primarykey: Id
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'Perfil a-z'
      criteria: 'Perfil ASC'
    -
      title: 'Perfil z-a'
      criteria: 'Perfil DESC'
  search_default: Id
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Perfil:
      title: Perfil
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
