# Module: CambioClienteFactura
# Document : modules\CambioClienteFactura\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 15.04.2012 00:47:17
#
---
CambioClienteFactura:
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Cambio de Cliente Factura
  id_video: cambioclientefactura
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: CambioClienteFactura
  table:
  primarykey:
  records_per_page: 15
  order_by:
  search_default:
  referenced_entities:
  columns: