# Module: ErpAlbaranesLineas
# Document : modules/ErpAlbaranesLineas/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:24
#
---
AlbaranesLineas:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDAlbaran
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDAlbaran
  controller: AlbaranesLineas
  action: Index
  template: index.html.twig
  parametros: ''
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Líneas de albaranes
  id_video: albaraneslineas
  url_video: null
  feature_list: true
  conection: ''
  entity: AlbaranesLineas
  table: ErpAlbaranesLineas
  primarykey: IDLinea
  linkBy: IDAlbaran
  records_per_page: 10
  order_by:
    -
      title: 'IDLinea a-z'
      criteria: 'IDLinea ASC'
    -
      title: 'IDLinea z-a'
      criteria: 'IDLinea DESC'
  search_default: IDLinea
  referenced_entities:
    - AlbaranesCab
    - Articulos
    - Almacenes
    - TiposVenta
    - ValoresSN
    - Agentes
    - Promociones
    - EstadosLineasAlbaranes
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDLinea:
      title: IDLinea
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDAlbaran:
      title: Albarán
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDAlbaran, entity: ErpAlbaranesCab, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDArticulo:
      title: Artículo
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 2, caption: IDArticulo, entity: ErpArticulos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Descripcion:
      title: Descripción
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Unidades:
      title: Unidades
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    UnidadMedida:
      title: Unidad Medida
      filter: true
      list: false
      visible: true
      updatable: true
      default: UMV
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '3', min: null, max: null, message: 'Valor Requerido' }
    Precio:
      title: Precio
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    PvpVigente:
      title: Pvp Vigente
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Descuento:
      title: Dctto
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Importe:
      title: Importe
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    ImporteCosto:
      title: Importe Costo
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    IDAlmacen:
      title: Almacén
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 3, caption: IDAlmacen, entity: ErpAlmacenes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Iva:
      title: Iva
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Recargo:
      title: Recargo
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    ComisionAgente:
      title: Comision Agente
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    ComisionMontador:
      title: Comision Montador
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    IDVenta:
      title: Tipo Venta
      filter: false
      list: false
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 4, caption: IDVenta, entity: ErpTiposVenta, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Comisionar:
      title: Comisionar
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 5, caption: Comisionar, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    IDAgente:
      title: Agente
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 6, caption: IDAgente, entity: ErpAgentes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDComercial:
      title: Comercial
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 7, caption: IDComercial, entity: ErpAgentes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDPromocion:
      title: Promoción
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 8, caption: IDPromocion, entity: ErpPromociones, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDEstado:
      title: Estado
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 9, caption: IDEstado, entity: EstadosLineasAlbaranes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    AltoAl:
      title: Alto Albarán
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    AnchoAl:
      title: Ancho Albarán
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    MtsAl:
      title: Mts Albarán
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    AltoFa:
      title: Alto Factura
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    AnchoFa:
      title: Ancho Factura
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    MtsFa:
      title: Mts Factura
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
