# Module: Noticias
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Noticias:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Noticias
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Noticias
  table: noticias
  primarykey: IDNoticia
  records_per_page: 10
  order_by: IDNoticia
  search_default: IDNoticia
  columns:
    - 
      title: IDNoticia
      field: IDNoticia
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: IDSucursal
      field: IDSucursal
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 000
      validator:
        nullable: NO
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Noticia
      field: Noticia
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Vigencia
      field: Vigencia
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Emergente
      field: Emergente
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
