# Module: FrecibidasLineas
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
FrecibidasLineas:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: FrecibidasLineas
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: FrecibidasLineas
  table: frecibidas_lineas
  linkBy: IDFactura
  primarykey: IDLinea
  records_per_page: 10
  order_by: IDLinea
  search_default: IDLinea
  columns:
    - 
      title: IDFactura
      field: IDFactura
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    - 
      title: IDLinea
      field: IDLinea
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: IDArticulo
      field: IDArticulo
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 25
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Descripcion
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Unidades
      field: Unidades
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 1.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Precio
      field: Precio
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.000
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Dcto
      field: Descuento
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Importe
      field: Importe
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Iva
      field: Iva
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    - 
      title: IDPedido
      field: IDPedido
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 00000000
      validator:
        nullable: NO
        type: integer
        length: 8
        min: null
        max: null
        message: Valor Requerido
    - 
      title: IDLineaPedido
      field: IDLineaPedido
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 00000000
      validator:
        nullable: NO
        type: integer
        length: 8
        min: null
        max: null
        message: Valor Requerido
