# Module: ErpRecibosClientes
# Document : modules/ErpRecibosClientes/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:29
#
---
RecibosClientes:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: true
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '1'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Recibo
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Recibo
  controller: ErpRecibosClientes
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: true
  permission_control: true
  favourite_control: NO
  help_file: help.html.twig
  title: Recibos de Clientes
  id_video: recibosclientes
  url_video: null
  feature_list: true
  conection: ''
  entity: RecibosClientes
  table: ErpRecibosClientes
  primarykey: IDRecibo
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: Vencimiento z-a
      criteria: Vencimiento DESC
    -
      title: Vencimiento a-z
      criteria: Vencimiento ASC
    -
      title: Factura a-z
      criteria: IDFactura ASC
    -
      title: Factura z-a
      criteria: IDFactura DESC
  search_default: IDRecibo
  referenced_entities:
    - Sucursales
    - FemitidasCab
    - Clientes
    - EstadosRecibos
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDRecibo:
      title: IDRecibo
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Recibo:
      title: Recibo
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '4', min: null, max: null, message: 'Valor Requerido' }
    IDSucursal:
      title: Sucursal
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 0, caption: Sucursal, entity: 'Agentes,<?php echo $_SESSION['usuarioPortal']['Id'];?>', method: getSucursales, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDFactura:
      title: Factura
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: N. Factura (%), entity: FemitidasCab, method: null, params: NumeroFactura, type: input, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDCliente:
      title: Cliente
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter:
        order: 2
        caption: Cliente (%)
        entity: Clientes
        method: null
        params: RazonSocial
        type: input
        event: null
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' } 
    NombreComercial:
      title: Nombre Comercial
      field: IDCliente
      filter: false
      list: true
      form: true
      aditional_filter:
        order: 3
        caption: N. Comercial (%)
        entity: Clientes
        method: null
        params: NombreComercial
        type: input
        event: null
      validator:
        nullable: true
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    IDComercial:
      title: Comercial
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter:
        order: 4
        caption: Comercial
        entity: 'Agentes,<?php echo $_SESSION['usuarioPortal']['Id'];?>'
        method: getComerciales
        params: RazonSocial
        type: select
        event: null
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }         
    Fecha:
      title: Fecha
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0000-00-00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter:
        order: 5
        caption: Fecha Ftra
        entity: null
        type: range
        operator: '>='
        default: '<?php echo '01/01/'.date('Y').',31/12/'.date('Y');?>'   
      validator: { nullable: NO, type: date, length: 10, min: null, max: null, message: 'Valor Requerido' }
    Vencimiento:
      title: Vencimiento
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0000-00-00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter:
        order: 7
        caption: Fecha Vcto
        entity: null
        type: range
        operator: '>='
        default: '<?php echo '01/01/'.date('Y').',31/12/'.date('Y');?>'
      validator: { nullable: NO, type: date, length: 10, min: null, max: null, message: 'Valor Requerido' }
    Importe:
      title: Importe
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Iban:
      title: Iban
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '34', min: null, max: null, message: 'Valor Requerido' }
    Bic:
      title: Bic
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '1', min: null, max: null, message: 'Valor Requerido' }      
    Mandato:
      title: Mandato
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: '35', min: null, max: null, message: 'Valor Requerido' }      
    FechaMandato:
      title: Fecha de mandato
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0000-00-00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 13, caption: FechaMandato, type: range, operator: '>=' }
      validator: { nullable: NO, type: date, length: 10, min: null, max: null, message: 'Valor Requerido' } 
    Asiento:
      title: Asiento
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '6', min: null, max: null, message: 'Valor Requerido' }
    Concepto:
      title: Concepto
      filter: true
      list: false
      visible: true
      updatable: true
      default: ''
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    IDEstado:
      title: Estado
      filter: false
      list: false
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter:
        order: 8
        caption: Estado
        entity: EstadosRecibos
        method: fetchAll
        params: Descripcion
        type: select
        event: null
        default: 0
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    IDRemesa:
      title: Remesa
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter:
        order: 9
        caption: Remesa
        entity: null
        method: null
        params: null
        type: input
        event: null      
      validator: { nullable: true, type: string, length: '14', min: null, max: null, message: 'Valor Requerido' }
    Remesar:
      title: Remesar
      filter: false
      list: false
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 9, caption: Remesar, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    CContable:
      title: CContable
      filter: true
      list: false
      visible: true
      updatable: true
      default: '0000000000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
