# Module: Agencias
# Document : modules/Agencias/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:23
#
---
Agencias:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Agencia
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Agencia
  controller: Agencias
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Agencias / Formas de Envío
  id_video: erpagencias
  url_video: null
  feature_list: YES
  conection: ''
  entity: Agencias
  table: ErpAgencias
  primarykey: IDAgencia
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'Agencia a-z'
      criteria: 'Agencia ASC'
    -
      title: 'Agencia z-a'
      criteria: 'Agencia DESC'
  search_default: Agencia
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDAgencia:
      title: IDAgencia
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Agencia:
      title: Agencia
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Fax:
      title: Fax
      filter: false
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Web:
      title: Web
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    CosteEstandar:
      title: Coste Estandar
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    UrlTracking:
      title: Url Tracking
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: null
      help: Dirección web para conocer el estado de los envíos
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    Uso:
      title: Disponible en
      filter: NO
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 2, caption: Disponible en, entity: UsoWeb, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '15', min: null, max: null, message: 'Valor Requerido' }       
