# Module: PlanContable
# Document : modules/PlanContable/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 26.01.2014 19:54:31
#
---
PlanContable:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Cuenta
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Cuenta
  fieldGeneratorMetatagDescription: Cuenta
  fieldGeneratorMetatagKeywords: Cuenta
  controller: PlanContable
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Plan Contable
  id_video: erpplancontable
  url_video: null
  feature_list: YES
  conection: ''
  entity: PlanContable
  table: ErpPlanContable
  primarykey: Id
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'Cuenta a-z'
      criteria: 'Cuenta ASC'
    -
      title: 'Cuenta z-a'
      criteria: 'Cuenta DESC'
  search_default: Cuenta
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDEjercicio:
      title: Ejercicio
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '4', min: null, max: null, message: 'Valor Requerido' }
      aditional_filter:
        order: 1
        caption: Ejercicio
        entity: EjerciciosContables
        method: fetchAll
        params: Titulo
        type: select      
    Cuenta:
      title: Cuenta
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Titulo:
      title: Título
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '100', min: null, max: null, message: 'Valor Requerido' }
    Debe:
      title: Debe
      filter: NO
      list: YES
      visible: true
      updatable: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '15', min: null, max: null, message: 'Valor Requerido' }
    Haber:
      title: Haber
      filter: NO
      list: YES
      visible: true
      updatable: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '15', min: null, max: null, message: 'Valor Requerido' }
    Saldo:
      title: Saldo
      filter: NO
      list: YES
      visible: true
      updatable: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '15', min: null, max: null, message: 'Valor Requerido' }