# Module: CambioComercial
# Document : modules\CambioComercial\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 15.04.2012 00:47:17
#
---
CambioComercial:
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Cambio de Comercial
  id_video: cambiocomercial
  url_video: null
  conection: 
  entity: CambioComercial
  table:
  primarykey:
  records_per_page: 15
  order_by:
  search_default:
  referenced_entities:
  columns: