# Module: Bancos
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Bancos:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Entidades Bancarias
  conection: empresas
  entity: Bancos
  table: bancos
  primarykey: IDBanco
  records_per_page: 15
  order_by:
    -
      title: Banco a-z
      criteria: Banco ASC
    -
      title: Banco z-a
      criteria: Banco DESC
    -
      title: Codigo a-z
      criteria: CodigoBanco ASC
    -
      title: Codigo z-a
      criteria: CodigoBanco DESC
  search_default: Banco
  columns:
    - 
      title: IDBanco
      field: IDBanco
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: Codigo
      field: CodigoBanco
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Banco
      field: Banco
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
