# Module: ErpBancos
# Document : modules/ErpBancos/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 01.04.2013 16:52:12
#
---
Bancos:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: CodigoBanco
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: CodigoBanco
  controller: Bancos
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Bancos
  id_video: bancos
  url_video: null
  feature_list: YES
  conection: ''
  entity: Bancos
  table: ErpBancos
  primarykey: IDBanco
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'Banco a-z'
      criteria: 'Banco ASC'
    -
      title: 'Banco z-a'
      criteria: 'Banco DESC'
  search_default: Banco
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDBanco:
      title: IDBanco
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    CodigoBanco:
      title: Código
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '4', min: null, max: null, message: 'Valor Requerido' }
    Banco:
      title: Banco
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
