# Module: Sms
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Sms:
  login_required: true
  permission_control: true
  help_file: help.html.twig
  title: Sms
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Sms
  table: sms
  primarykey: IDSms
  records_per_page: 10
  order_by: IDSms
  search_default: IDSms
  columns:
    - 
      title: IDSms
      field: IDSms
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: CuentaSms
      field: CuentaSms
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: IDUsuario
      field: IDUsuario
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Fecha
      field: Fecha
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: datetime
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Remite
      field: Remite
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 11
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Para
      field: Para
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Mensaje
      field: Mensaje
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 160
        min: null
        max: null
        message: Valor Requerido
    - 
      title: EnviadoOk
      field: EnviadoOk
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Resultado
      field: Resultado
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: NDestinatarios
      field: NDestinatarios
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
