# Module: Favoritos
# Document : modules\Favoritos\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 16.01.2012 23:56:05
#
---
Favoritos:
  login_required: NO
  permission_control: false
  help_file: help.html.twig
  title: Favoritos
  id_video: null
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Favoritos
  table: favoritos
  primarykey: Id
  records_per_page: 15
  order_by:
    -
      title: Titulo a-z
      criteria: Titulo ASC
    -
      title: Titulo z-a
      criteria: Titulo DESC
  search_default: Id
  referenced_entities:
    -
      entity: Agentes
  columns:
    -
      title: Id
      field: Id
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: Agente
      field: IDAgente
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 1
        caption: Agente
        entity: Agentes
        method: fetchAll
        params: Nombre
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: Titulo
      field: Titulo
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: Url
      field: Url
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 100
        min: null
        max: null
        message: Valor Requerido
    -
      title: Accesos
      field: Accesos
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
