alter table ErpAlmacenesMapas
  DROP CreatedBy, DROP CreatedAt, DROP ModifiedBy, DROP ModifiedAt;
  
alter table ErpAlmacenesMapas
  ADD `Observations` text,
  ADD `PrimaryKeyMD5` varchar(100) DEFAULT NULL,
  ADD `IsDefault` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `IsSuper` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `Checked` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `Publish` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `BelongsTo` int(11) NOT NULL DEFAULT '0',
  ADD `AllowsChildren` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `CreatedBy` int(4) NOT NULL DEFAULT '0',
  ADD `CreatedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ADD `ModifiedBy` int(4) NOT NULL DEFAULT '0',
  ADD `ModifiedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ADD `Deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `DeletedBy` int(4) NOT NULL DEFAULT '0',
  ADD `DeletedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ADD `PrintedBy` int(4) NOT NULL DEFAULT '0',
  ADD `PrintedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ADD `EmailedBy` int(4) NOT NULL DEFAULT '0',
  ADD `EmailedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ADD `Privacy` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresPrivacy,IDTipo',
  ADD `SortOrder` int(11) NOT NULL DEFAULT '0',
  ADD `PublishedAt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ADD `ActiveFrom` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ADD `ActiveTo` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ADD `UrlPrefix` varchar(255) DEFAULT NULL,
  ADD `LockUrlPrefix` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `Slug` varchar(255) DEFAULT NULL,
  ADD `LockSlug` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `UrlFriendly` varchar(255) DEFAULT NULL,
  ADD `UrlHeritable` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `NumberVisits` int(11) NOT NULL DEFAULT '0',
  ADD `MetatagTitle` varchar(255) DEFAULT NULL,
  ADD `LockMetatagTitle` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `MetatagKeywords` varchar(255) DEFAULT NULL,
  ADD `MetatagDescription` varchar(255) DEFAULT NULL,
  ADD `MetatagTitleSimple` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `MetatagTitlePosition` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresDchaIzq,IDTipo',
  ADD `ShowOnSitemap` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `ImportanceSitemap` varchar(5) DEFAULT '0.5',
  ADD `ChangeFreqSitemap` varchar(25) DEFAULT 'monthly' COMMENT 'Abstract,ValoresChangeFreq,IDTipo',
  ADD `ShowGalery` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `ShowDocuments` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `ShowRelatedLinks` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `ShowRelatedContents` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `ShowPublishedAt` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `AccessProfileList` varchar(100) NOT NULL DEFAULT 'perfiles:\n  1: 1\n  2: 2\n',
  ADD `AccessProfileListWeb` varchar(100) NOT NULL DEFAULT 'perfiles:\n  1: 1\n',
  ADD `UrlTarget` varchar(255) DEFAULT NULL,
  ADD `UrlParameters` varchar(255) DEFAULT NULL,
  ADD `UrlRequestMethod` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,RequestMethods,IDTipo',
  ADD `UrlOrigin` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,RequestOrigins,IDTipo',
  ADD `UrlTargetBlank` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `UrlIsHttps` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abstract,ValoresSN,IDTipo',
  ADD `CodigoAppAsociada` varchar(15) DEFAULT NULL COMMENT 'db,CpanAplicaciones,CodigoApp',
  ADD `IdAlbumExterno` bigint(11) DEFAULT NULL,
  ADD `IdSliderAsociado` bigint(11) DEFAULT NULL,
  ADD `IdSeccionEnlaces` bigint(11) DEFAULT NULL,
  ADD `IdSeccionVideos` bigint(11) DEFAULT NULL,
  ADD `DateTimeLastVisit` bigint(11) NOT NULL DEFAULT '0',
  ADD `RevisitAfter` varchar(20) DEFAULT NULL,
  ADD `NivelJerarquico` int(4) DEFAULT '0',

  ADD UNIQUE `PrimaryKeyMD5` (`PrimaryKeyMD5`),
  ADD INDEX `IsDefault` (`IsDefault`),
  ADD INDEX `IsSuper` (`IsSuper`),
  ADD INDEX `Checked` (`Checked`),
  ADD INDEX `Publish` (`Publish`),
  ADD INDEX `BelongsTo` (`BelongsTo`),
  ADD INDEX `AllowsChildren` (`AllowsChildren`),
  ADD INDEX `Deleted` (`Deleted`),
  ADD INDEX `Privacy` (`Privacy`),
  ADD INDEX `SortOrder` (`SortOrder`),
  ADD INDEX `LockUrlPrefix` (`LockUrlPrefix`),
  ADD INDEX `LockSlug` (`LockSlug`),
  ADD INDEX `UrlHeritable` (`UrlHeritable`),
  ADD INDEX `LockMetatagTitle` (`LockMetatagTitle`),
  ADD INDEX `MetatagTitleSimple` (`MetatagTitleSimple`),
  ADD INDEX `MetatagTitlePosition` (`MetatagTitlePosition`),
  ADD INDEX `ShowOnSitemap` (`ShowOnSitemap`),
  ADD INDEX `ChangeFreqSitemap` (`ChangeFreqSitemap`),
  ADD INDEX `ShowGalery` (`ShowGalery`),
  ADD INDEX `ShowDocuments` (`ShowDocuments`),
  ADD INDEX `ShowRelatedLinks` (`ShowRelatedLinks`),
  ADD INDEX `ShowRelatedContents` (`ShowRelatedContents`),
  ADD INDEX `ShowPublishedAt` (`ShowPublishedAt`),
  ADD INDEX `UrlRequestMethod` (`UrlRequestMethod`),
  ADD INDEX `UrlOrigin` (`UrlOrigin`),
  ADD INDEX `UrlTargetBlank` (`UrlTargetBlank`),
  ADD INDEX `UrlIsHttps` (`UrlIsHttps`),
  ADD INDEX `CodigoAppAsociada` (`CodigoAppAsociada`);
