# Module: Sucursales
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Sucursales:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Sucursales
  conection: empresas
  entity: Sucursales
  table: sucursales
  primarykey: IDSucursal
  linkBy: IDEmpresa
  records_per_page: 9999
  order_by: IDEmpresa
  search_default: IDEmpresa
  columns:
    - 
      title: Sucursal
      field: IDSucursal
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 000
      validator:
        nullable: YES
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Empresa
      field: IDEmpresa
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 000
      validator:
        nullable: NO
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Nombre
      field: Nombre
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Direccion
      field: Direccion
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Poblacion
      field: Poblacion
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 30
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Provincia
      field: IDProvincia
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: null
        length: 2
        min: 1
        max: 999
        message: Valor Requerido
    - 
      title: Codigo Postal
      field: CodigoPostal
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000000000
      validator:
        nullable: NO
        type: string
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Telefono
      field: Telefono
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: YES
        type: string
        length: 30
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Fax
      field: Fax
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: YES
        type: string
        length: 30
        min: null
        max: null
        message: Valor Requerido
    - 
      title: EMail
      field: EMail
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: YES
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Responsable
      field: IDResponsable
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: 1
        max: 9999
        message: Valor Requerido
    - 
      title: Cta Contable Clientes
      field: CtaContableClientes
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: string
        length: 3
        min: null
        max: null
        message: Valor Requerido
    -
      title: Cta Contable Ventas
      field: CtaContableVentas
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: string
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Cta Contable Compras
      field: CtaContableCompras
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: string
        length: 10
        min: null
        max: null
        message: Valor Requerido