# Module: ErpSucursales
# Document : modules/ErpSucursales/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:29
#
---
Sucursales:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Nombre
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Nombre
  controller: Sucursales
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Sucursales
  id_video: sucursales
  url_video: null
  feature_list: YES
  conection: ''
  entity: Sucursales
  table: ErpSucursales
  primarykey: IDSucursal
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'IDSucursal a-z'
      criteria: 'IDSucursal ASC'
    -
      title: 'IDSucursal z-a'
      criteria: 'IDSucursal DESC'
  search_default: IDSucursal
  referenced_entities:
    - ErpProvincias
    - CpanUsuarios
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDSucursal:
      title: IDSucursal
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Nombre:
      title: Nombre
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    Direccion:
      title: Dirección
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    IDPais:
      title: País
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: 68
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: País, entity: Paises, method: fetchAll, params: Pais, type: select, operator: '=', event: null }        
    IDPoblacion:
      title: Población
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: Población, entity: Provincias, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }      
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    IDProvincia:
      title: Provincia
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: 18
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDProvincia, entity: ErpProvincias, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    CodigoPostal:
      title: Código Postal
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Telefono:
      title: Teléfono
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    Fax:
      title: Fax
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '30', min: null, max: null, message: 'Valor Requerido' }
    EMail:
      title: EMail
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    IDResponsable:
      title: Responsable
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 2, caption: IDResponsable, entity: Agentes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    CtaContableClientes:
      title: Cta Contable Clientes
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '430'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }      
    CtaContableVentas:
      title: Cta Contable Ventas
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '70000000001'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
    CtaContableCompras:
      title: Cta Contable Compras
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '6000000001'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '10', min: null, max: null, message: 'Valor Requerido' }
