# Module: AlbaranesCab
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
AlbaranesCab:
  login_required: YES
  permission_control: YES
  favourite_control: YES
  help_file: help.html.twig
  title: Albaranes de Venta
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: AlbaranesCab
  table: albaranes_cab
  primarykey: IDAlbaran
  records_per_page: 20
  order_by:
    -
      title: Número z-a
      criteria: NumeroAlbaran DESC
    -
      title: Número a-z
      criteria: NumeroAlbaran ASC
    -
      title: Fecha z-a
      criteria: Fecha DESC
    -
      title: Fecha a-z
      criteria: Fecha ASC
  search_default: IDAlbaran
  columns:
    -
      title: IDAlbaran
      field: IDAlbaran
      filter: NO
      list: NO
      form: YES
      default: null
      validator: null
    -
      title: IDContador
      field: IDContador
      filter: NO
      list: NO
      form: YES
      default: 000
      validator:
        nullable: NO
        type: string
        length: 15
        min: 1
        max: 999999
        message: Valor Requerido
    -
      title: Número
      field: NumeroAlbaran
      filter: YES
      list: YES
      form: YES
      default: 000
      validator:
        nullable: YES
        type: string
        length: 15
        min: null
        max: null
        message: Valor Requerido
    -
      title: Sucursal
      field: IDSucursal
      filter: NO
      list: YES
      form: YES
      default: 000
      validator:
        nullable: NO
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 1
        caption: Sucursal
        entity: 'Agentes,<?php echo $_SESSION['usuarioPortal']['Id'];?>'
        method: getSucursales
        params:
        type: select
    -
      title: Almacen
      field: IDAlmacen
      filter: NO
      list: YES
      form: YES
      default: 000
      validator:
        nullable: NO
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 2
        caption: Almacén
        entity: 'Agentes,<?php echo $_SESSION['usuarioPortal']['Id'];?>'
        method: getAlmacenes
        params: null
        type: select
    -
      title: Agente
      field: IDAgente
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 3
        caption: Usuario
        entity: Agentes
        method: fetchAll
        params: Nombre
        type: select
    -
      title: Comercial
      field: IDComercial
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 4
        caption: Comercial
        entity: Agentes
        method: getComerciales
        params:
        type: select
    -
      title: Fecha
      field: Fecha
      filter: NO
      list: YES
      form: YES
      default: 0000-00-00
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 5
        caption: Fecha
        entity: null
        type: range
        default: '<?php echo '01/01/'.date('Y').',31/12/'.date('Y');?>'
        operator: '>='
    -
      title: Fecha de Entrega
      field: FechaEntrega
      filter: NO
      list: YES
      form: YES
      default: 0000-00-00
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    -
      title: Cliente
      field: IDCliente
      filter: NO
      list: YES
      form: YES
      default: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 7
        caption: Cliente (%)
        entity: Clientes
        method: null
        params: RazonSocial
        type: input
    -
      title: Direccion de Entrega
      field: IDDirec
      filter: NO
      list: YES
      form: YES
      default: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Importe
      field: Importe
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descuento
      field: Descuento
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: BaseImponible1
      field: BaseImponible1
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: YES
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Iva1
      field: Iva1
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: YES
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: CuotaIva1
      field: CuotaIva1
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: YES
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Recargo1
      field: Recargo1
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: YES
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: CuotaRecargo1
      field: CuotaRecargo1
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: YES
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: BaseImponible2
      field: BaseImponible2
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Iva2
      field: Iva2
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: CuotaIva2
      field: CuotaIva2
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Recargo2
      field: Recargo2
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: CuotaRecargo2
      field: CuotaRecargo2
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: BaseImponible3
      field: BaseImponible3
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Iva3
      field: Iva3
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: CuotaIva3
      field: CuotaIva3
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Recargo3
      field: Recargo3
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: CuotaRecargo3
      field: CuotaRecargo3
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: TotalBases
      field: TotalBases
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: TotalIva
      field: TotalIva
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: TotalRecargo
      field: TotalRecargo
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Total
      field: Total
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Estado
      field: IDEstado
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 26
        caption: Estado
        entity: EstadosAlbaranes
        method: fetchAll
        params: Descripcion
        type: select
    -
      title: Factura
      field: IDFactura
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: YES
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 27
        caption: Factura (%)
        entity: FemitidasCab
        method: null
        params: NumeroFactura
        type: input
    -
      title: Observaciones
      field: Observaciones
      filter: NO
      list: YES
      form: YES
      default: null
      validator:
        nullable: YES
        type: string
        length: null
        min: null
        max: null
        message: Valor Requerido
    -
      title: Peso
      field: Peso
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Volumen
      field: Volumen
      filter: NO
      list: YES
      form: YES
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Bultos
      field: Bultos
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: Expedicion
      field: Expedicion
      filter: NO
      list: YES
      form: YES
      default: null
      validator:
        nullable: YES
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: Agencia
      field: IDAgencia
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: Clave
      field: Clave
      filter: NO
      list: NO
      form: YES
      default: null
      validator:
        nullable: YES
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: Facturar
      field: Facturar
      filter: NO
      list: NO
      form: YES
      default: 1
      validator:
        nullable: YES
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: Forma de Pago
      field: IDFP
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: 1
        max: 9999
        message: Valor Requerido
    -
      title: Ruta Reparto
      field: IDRutaReparto
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: YES
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 28
        caption: Ruta Reparto
        entity: RutasReparto
        method: fetchAll
        params:
        type: select
    -
      title: Repartidor
      field: IDRepartidor
      filter: NO
      list: YES
      form: YES
      default: 0
      validator:
        nullable: YES
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 29
        caption: Repartidor
        entity: Agentes
        method: getRepartidores
        params:
        type: select