# Module: Agentes
# Document : modules/Agentes/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:30
#
---
Agentes:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IdUsuario
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IdUsuario
  controller: Agentes
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Usuarios
  id_video: usuarios
  url_video: null
  feature_list: true
  conection: ''
  entity: Agentes
  table: ErpUsuarios
  primarykey: IDAgente
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'IDAgente a-z'
      criteria: 'IDAgente ASC'
    -
      title: 'IDAgente z-a'
      criteria: 'IDAgente DESC'
  search_default: IDAgente
  referenced_entities:
    - Perfiles
    - Roles
    - UsuariosTipos
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDAgente:
      title: Usuario
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Activo:
      title: Activo
      filter: true
      list: true
      visible: true
      updatable: true
      default: 1
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: Activo, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }      
    IDPerfil:
      title: Perfil
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDPerfil, entity: Perfiles, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDRol:
      title: Rol
      filter: false
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 2, caption: IDRol, entity: Roles, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDTipo:
      title: Tipo
      filter: false
      list: false
      visible: true
      updatable: true
      default: 0
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 3, caption: IdTipoUsuario, entity: ErpUsuariosTipos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDSucursal:
      title: Sucursal
      filter: false
      list: false
      visible: true
      updatable: true
      default: 1
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 3, caption: Sucursal, entity: Sucursales, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }      
    IDAlmacen:
      title: Almacén
      filter: false
      list: false
      visible: true
      updatable: true
      default: 1
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 4, caption: Almacén, entity: Almacenes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }      
