# Module: TiposIva
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
TiposIva:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Tipo
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Tipo
  controller: TiposIva
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Tipos de Iva
  id_video: tiposIva
  url_video: null
  feature_list: YES
  conection: ''
  entity: TiposIva
  table: ErpTiposIva
  primarykey: IDIva
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: Tipo a-z
      criteria: Tipo ASC
    -
      title: Tipo z-a
      criteria: Tipo DESC
  search_default: Tipo
  columns:
    IDIva:
      title: Codigo
      filter: NO
      list: NO
      visible: false
      updatable: false
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    Tipo:
      title: Tipo
      filter: YES
      list: YES
      visible: true
      updatable: true    
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 30
        min: null
        max: null
        message: Valor Requerido
    Iva:
      title: Iva
      filter: NO
      list: YES
      visible: true
      updatable: true    
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: 0
        max: 99
        message: Valor Requerido (0-99)
    Recargo:
      title: Recargo
      filter: NO
      list: YES
      visible: true
      updatable: true      
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: 0
        max: 20
        message: Valor Requerido (0-20)
    Retencion:
      title: Retención
      filter: NO
      list: YES
      visible: true
      updatable: true     
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: 0
        max: 99
        message: Valor Requerido (0-99)
