# Module: Tarifas
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Tarifas:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Tarifas
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Tarifas
  table: tarifas
  primarykey: IDTarifa
  records_per_page: 10
  order_by:
    -
      title: Descripcion a-z
      criteria: Descripcion ASC
    -
      title: Descripcion z-a
      criteria: Descripcion DESC
  search_default: Descripcion
  columns:
    - 
      title: Codigo
      field: IDTarifa
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: Descripcion
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Tipo
      field: Tipo
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: YES
        type: integer
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Valor
      field: Valor
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.000
      validator:
        nullable: NO
        type: decimal
        length: 7
        min: null
        max: null
        message: Valor Requerido
