# Module: ErpTpvs
# Document : modules/ErpTpvs/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:30
#
---
Tpvs:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDSucursal
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDSucursal
  controller: Tpvs
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Tpvs y datáfonos
  id_video: tpvs
  url_video: null
  feature_list: YES
  conection: ''
  entity: Tpvs
  table: ErpTpvs
  primarykey: IDTpv
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: Sucursal a-z
      criteria: IDSucursal ASC
    -
      title: Sucursal z-a
      criteria: IDSucursal DESC
  search_default: IDTpv
  referenced_entities:
    - Sucursales
    - ValoresSN
    - ErpDatafonos
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDTpv:
      title: IDTpv
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDSucursal:
      title: Sucursal
      filter: NO
      list: YES
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDSucursal, entity: ErpSucursales, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Nombre:
      title: Nombre
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    AperturaCajon:
      title: Apertura Cajón
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    SaltoPagina:
      title: Salto Página
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 2, caption: SaltoPagina, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    Estilo:
      title: Estilo
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    IDDataFono1:
      title: DataFono1
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 3, caption: IDDataFono1, entity: ErpDatafonos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: YES, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDDataFono2:
      title: DataFono2
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 4, caption: IDDataFono2, entity: ErpDatafonos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: YES, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDDataFono3:
      title: DataFono3
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 5, caption: IDDataFono3, entity: ErpDatafonos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: YES, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDDataFono4:
      title: DataFono4
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 6, caption: IDDataFono4, entity: ErpDatafonos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: YES, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
 