# Module: TiposMvtosAlmacen
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
TiposMvtosAlmacen:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Tipos de Movimientos de Almacén
  conection: empresas
  entity: TiposMvtosAlmacen
  table: tipos_mvtos_almacen
  primarykey: Id
  records_per_page: 10
  order_by:
    -
      title: Signo a-z
      criteria: Signo ASC
    -
      title: Descripcion a-z
      criteria: Descripcion ASC
    -
      title: Descripcion z-a
      criteria: Descripcion DESC
  search_default: Descripcion
  columns:
    - 
      title: Id
      field: Id
      filter: NO
      list: NO
      form: YES
      validator: null
    - 
      title: Signo
      field: Signo
      filter: NO
      list: YES
      form: YES
      validator:
        nullable: NO
        type: string
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Uso
      field: Uso
      filter: NO
      list: YES
      form: YES
      validator:
        nullable: NO
        type: string
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descripcion
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Tipo Documento
      field: TipoDocumento
      filter: NO
      list: YES
      form: YES
      validator:
        nullable: YES
        type: string
        length: 25
        min: null
        max: null
        message: Valor Requerido
