# Module: ErpEjerciciosContables
# Document : modules/ErpEjerciciosContables/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 26.01.2014 21:12:08
#
---
EjerciciosContables:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Titulo
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Titulo
  fieldGeneratorMetatagDescription: Titulo
  fieldGeneratorMetatagKeywords: Titulo
  controller: EjerciciosContables
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Ejercicios Contables
  id_video: erpejercicioscontables
  url_video: null
  feature_list: true
  conection: ''
  entity: EjerciciosContables
  table: ErpEjerciciosContables
  primarykey: Id
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: 'Titulo a-z'
      criteria: 'Titulo ASC'
    -
      title: 'Titulo z-a'
      criteria: 'Titulo DESC'
  search_default: Titulo
  referenced_entities:
    - ValoresSN
  columns:
    Id:
      title: Id
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Titulo:
      title: Título
      filter: true
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: string, length: '50', min: null, max: null, message: 'Valor Requerido' }
    FechaInicio:
      title: Fecha Inicio
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0000-00-00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 1, caption: FechaInicio, type: range, operator: '>=' }
      validator: { nullable: false, type: date, length: 10, min: null, max: null, message: 'Valor Requerido' }
    FechaFin:
      title: Fecha Fin
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0000-00-00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 3, caption: FechaFin, type: range, operator: '>=' }
      validator: { nullable: true, type: date, length: 10, min: null, max: null, message: 'Valor Requerido' }
    Activo:
      title: Activo
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 5, caption: Activo, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '2', min: null, max: null, message: 'Valor Requerido' }
    Cerrado:
      title: Cerrado
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      '#aditional_filter': { order: 6, caption: Cerrado, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '2', min: null, max: null, message: 'Valor Requerido' }
