# Module: EmpresasAlmacenes
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
EmpresasAlmacenes:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Almacenes
  conection: empresas
  entity: EmpresasAlmacenes
  table: empresas_almacenes
  primarykey: Id
  linkBy: IDEmpresa
  records_per_page: 10
  order_by: IDEmpresa
  search_default: IDEmpresa
  columns:
    - 
      title: Id
      field: Id
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: Empresa
      field: IDEmpresa
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 3
        min: 1
        max: 999
        message: Valor Requerido
    - 
      title: Almacen
      field: IDAlmacen
      filter: YES
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 3
        min: 1
        max: 999
        message: Valor Requerido
