# Module: FemitidasLineas
# Document : modules\FemitidasLineas\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 14.02.2012 11:40:03
#
---
FemitidasLineas:
  login_required: true
  permission_control: true
  help_file: help.html.twig
  title: FemitidasLineas
  id_video: femitidaslineas
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: FemitidasLineas
  table: femitidas_lineas
  primarykey: IDLinea
  records_per_page: 10
  order_by: IDLinea
  search_default: IDLinea
  referenced_entities:
    -
      entity: Articulos
    -
      entity: AlbaranesCab
    -
      entity: TiposVenta
    -
      entity: ValoresSN
    -
      entity: Agentes
    -
      entity: Promociones
  columns:
    -
      title: IDFactura
      field: IDFactura
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDLinea
      field: IDLinea
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: IDArticulo
      field: IDArticulo
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descripcion
      field: Descripcion
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: false
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: Unidades
      field: Unidades
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 1.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Precio
      field: Precio
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.000
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Dcto
      field: Descuento
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Importe
      field: Importe
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: ImporteCosto
      field: ImporteCosto
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDAlbaran
      field: IDAlbaran
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 00000000000
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDLineaAlbaran
      field: IDLineaAlbaran
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Iva
      field: Iva
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: Recargo
      field: Recargo
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: ComisionAgente
      field: ComisionAgente
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: ComisionMontador
      field: ComisionMontador
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDVenta
      field: IDVenta
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: Comisionar
      field: Comisionar
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: false
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDAgente
      field: IDAgente
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDComercial
      field: IDComercial
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDPromocion
      field: IDPromocion
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: AltoAl
      field: AltoAl
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.000
      validator:
        nullable: false
        type: decimal
        length: 6
        min: null
        max: null
        message: Valor Requerido
    -
      title: AnchoAl
      field: AnchoAl
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.000
      validator:
        nullable: false
        type: decimal
        length: 6
        min: null
        max: null
        message: Valor Requerido
    -
      title: MtsAl
      field: MtsAl
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.000
      validator:
        nullable: false
        type: decimal
        length: 6
        min: null
        max: null
        message: Valor Requerido
    -
      title: AltoFa
      field: AltoFa
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.000
      validator:
        nullable: false
        type: decimal
        length: 6
        min: null
        max: null
        message: Valor Requerido
    -
      title: AnchoFa
      field: AnchoFa
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.000
      validator:
        nullable: false
        type: decimal
        length: 6
        min: null
        max: null
        message: Valor Requerido
    -
      title: MtsFa
      field: MtsFa
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.000
      validator:
        nullable: false
        type: decimal
        length: 6
        min: null
        max: null
        message: Valor Requerido
