# Module: Expediciones
# Document : modules\Expediciones\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 23.02.2012 12:19:54
#
---
Expediciones:
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Expediciones
  id_video: expediciones
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Expediciones
  table: expediciones
  primarykey: IDLinea
  records_per_page: 10
  order_by: IDLinea
  search_default: IDLinea
  referenced_entities:
    -
      entity: AlbaranesCab
    -
      entity: AlbaranesLineas
    -
      entity: Almacenes
    -
      entity: Agentes
    -
      entity: Lotes
    -
      entity: AlmacenesMapas
  columns:
    -
      title: IDLinea
      field: IDLinea
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: IDAlbaran
      field: IDAlbaran
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDLineaAlbaran
      field: IDLineaAlbaran
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDAlmacen
      field: IDAlmacen
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDAlmacenero
      field: IDAlmacenero
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: Unidades
      field: Unidades
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Kilos
      field: Kilos
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Cajas
      field: Cajas
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Pales
      field: Pales
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDLote
      field: IDLote
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 5
        caption: IDLote
        entity: Lotes
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: false
        type: integer
        length: 8
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDUbicacion
      field: IDUbicacion
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 8
        min: null
        max: null
        message: Valor Requerido
    -
      title: Temperatura
      field: Temperatura
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: -20.00
      validator:
        nullable: false
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: Expedida
      field: Expedida
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: false
        type: decimal
        length: 1
        min: 0
        max: 1
        message: Valor Requerido
