# Module: Idiomas
# Document : modules/Idiomas/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 02.02.2014 01:32:22
#
---
Idiomas:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Codigo
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Codigo
  fieldGeneratorMetatagDescription: Codigo
  fieldGeneratorMetatagKeywords: Codigo
  controller: Idiomas
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Idiomas
  id_video: idiomas
  url_video: null
  feature_list: YES
  conection: ''
  entity: Idiomas
  table: ErpIdiomas
  primarykey: IDIdioma
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'Idioma a-z'
      criteria: 'Idioma ASC'
    -
      title: 'Idioma z-a'
      criteria: 'Idioma DESC'
  search_default: Idioma
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDIdioma:
      title: IDIdioma
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Codigo:
      title: Código
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '2', min: null, max: null, message: 'Valor Requerido' }
    Idioma:
      title: Idioma
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
