# Module: Circulares
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 16-11-2013
#
---
Circulares:
  login_required: true
  permission_control: true
  favourite_control: true
  help_file: help.html.twig
  title: Generador de Circulares
  conection: 
  entity: 
  table: 
  primarykey: 
  records_per_page: 
  order_by:
  search_default:
  columns: