# Module: ErpCajaArqueos
# Document : modules/ErpCajaArqueos/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:24
#
---
CajaArqueos:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '1'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDSucursal
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDSucursal
  controller: CajaArqueos
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Arqueos de Caja
  id_video: cajaarqueos
  url_video: null
  feature_list: true
  conection: ''
  entity: CajaArqueos
  table: ErpCajaArqueos
  primarykey: IDArqueo
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: Sucursal,Tpv,Dia z-a
      criteria: IDSucursal,IDTpv,Dia DESC
    -
      title: Sucursal,Tpv,Dia a-z
      criteria: IDSucursal,IDTpv,Dia ASC
  search_default: IDArqueo
  search_default: IDArqueo
  referenced_entities:
    - Sucursales
    - Tpvs
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDArqueo:
      title: IDArqueo
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDSucursal:
      title: Sucursal
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDSucursal, entity: ErpSucursales, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDTpv:
      title: Tpv
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter:
        order: 0
        caption: Fecha
        entity: null
        type: input
        default: 0
        operator: '>='   
      validator: { nullable: false, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Dia:
      title: Dia
      filter: false
      list: true
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: Fecha, entity: null, type: range, operator: '>=' }     
      validator: { nullable: false, type: date, length: 10, min: null, max: null, message: 'Valor Requerido' }
    CajaCerrada:
      title: Caja Cerrada
      filter: false
      list: true 
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 5, caption: CajaCerrada, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: false, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    SaldoApertura:
      title: Saldo Apertura
      filter: true
      list: true
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    SumaMvtos:
      title: Suma Mvtos
      filter: true
      list: true
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    SaldoCierre:
      title: Saldo Cierre
      filter: true
      list: true
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: false, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Observaciones:
      title: Observaciones
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: false, min: null, max: null, message: 'Valor Requerido' }
