# Module: ErpInventariosCab
# Document : modules/ErpInventariosCab/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:26
#
---
InventariosCab:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '1'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDInventario
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDInventario
  controller: InventariosCab
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: true
  permission_control: true
  favourite_control: NO
  help_file: help.html.twig
  title: Inventarios
  id_video: inventarioscab
  url_video: null
  feature_list: true
  conection: ''
  entity: InventariosCab
  table: ErpInventariosCab
  primarykey: IDInventario
  linkBy: ''
  records_per_page: 10
  order_by:
    -
      title: Fecha z-a
      criteria: Fecha DESC    
    -
      title: Fecha a-z
      criteria: Fecha ASC
    -
      title: Número z-a
      criteria: IDInventario DESC
    -
      title: Número a-z
      criteria: IDInventario ASC
  search_default: IDInventario
  referenced_entities:
    - Almacenes
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDInventario:
      title: IDInventario
      visible: false
      updatable: false
      filter: false
      list: false
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDAlmacen:
      title: Almacén
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 1, caption: Almacén, entity: 'Agentes,<?php echo $_SESSION['usuarioPortal']['Id'];?>', method: getAlmacenes, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '35', min: null, max: null, message: 'Valor Requerido' }
    Fecha:
      title: Fecha
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0000-00-00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 2, caption: Fecha, type: range, operator: '>=' }
      validator: { nullable: NO, type: date, length: 10, min: null, max: null, message: 'Valor Requerido' }
    Cerrado:
      title: Cerrado
      filter: false
      list: true
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      aditional_filter: { order: 4, caption: Cerrado, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '2', min: null, max: null, message: 'Valor Requerido' }
    Comentarios:
      title: Comentarios
      filter: true
      list: false
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: true, type: string, length: false, min: null, max: null, message: 'Valor Requerido' }
