# Module: RutasVentasClientes
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Rutas:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Rutas de Ventas
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: RutasVentas
  table: rutas_ventas
  primarykey: Id
  records_per_page: 10
  order_by: Id
  search_default: Id
  columns:
    - 
      title: Id
      field: Id
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: Comercial
      field: IDComercial
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Dia
      field: Dia
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Cliente
      field: IDCliente
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
