# Module: ExpedirCab
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
ExpedirCab:
  login_required: true
  permission_control: true
  help_file: help.html.twig
  title: Expedir Mercancía
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: AlbaranesCab
  table: albaranes_cab
  primarykey: IDAlbaran
  records_per_page: 20
  order_by: Fecha
  search_default: IDAlbaran
  columns:
    - 
      title: Albaran
      field: IDAlbaran
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: Sucursal
      field: IDSucursal
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 000
      validator:
        nullable: false
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Almacen
      field: IDAlmacen
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 000
      validator:
        nullable: false
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Agente
      field: IDAgente
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Comercial
      field: IDComercial
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Fecha
      field: Fecha
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00
      validator:
        nullable: false
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Fecha de Entrega
      field: FechaEntrega
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00
      validator:
        nullable: false
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Cliente
      field: IDCliente
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Direccion de Entrega
      field: IDDirec
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Importe
      field: Importe
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Descuento
      field: Descuento
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: BaseImponible1
      field: BaseImponible1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Iva1
      field: Iva1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaIva1
      field: CuotaIva1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Recargo1
      field: Recargo1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaRecargo1
      field: CuotaRecargo1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: BaseImponible2
      field: BaseImponible2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Iva2
      field: Iva2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaIva2
      field: CuotaIva2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Recargo2
      field: Recargo2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaRecargo2
      field: CuotaRecargo2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: BaseImponible3
      field: BaseImponible3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Iva3
      field: Iva3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaIva3
      field: CuotaIva3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Recargo3
      field: Recargo3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaRecargo3
      field: CuotaRecargo3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: TotalBases
      field: TotalBases
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: TotalIva
      field: TotalIva
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: TotalRecargo
      field: TotalRecargo
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Total
      field: Total
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Estado
      field: IDEstado
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Factura
      field: IDFactura
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: false
        type: string
        length: 8
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Observaciones
      field: Observaciones
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Peso
      field: Peso
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Volumen
      field: Volumen
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: false
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Bultos
      field: Bultos
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Expedicion
      field: Expedicion
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Agencia
      field: IDAgencia
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Clave
      field: Clave
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: FActualizacion
      field: FActualizacion
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00 00:00:00
      validator:
        nullable: false
        type: datetime
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Facturar
      field: Facturar
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 1
      validator:
        nullable: false
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Forma de Pago
      field: IDFP
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: false
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
