# Module: Documentos
# Document : modules\Documentos\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 16.04.2012 00:18:47
#
---
Documentos:
  login_required: true
  permission_control: true
  favourite_control: false
  help_file: help.html.twig
  title: Documentos
  id_video: documentos
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Documentos
  table: documentos
  primarykey: Id
  records_per_page: 10
  order_by:
    -
      title: Entidad a-z
      criteria: Entidad ASC
    -
      title: Entidad z-a
      criteria: Entidad DESC
  search_default: Id
  referenced_entities:
  columns:
    -
      title: Id
      field: Id
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
    -
      title: Entidad
      field: Entidad
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: false
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: IdEntidad
      field: IdEntidad
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Orden
      field: Orden
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: false
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: PathName
      field: PathName
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: false
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: Texto Pie
      field: TextoPie
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: false
        type: string
        length:
        min: null
        max: null
        message: Valor Requerido
    -
      title: Title
      field: Title
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: false
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: Alt
      field: Alt
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: false
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
