# Module: ErpPstoLineas
# Document : modules/ErpPstoLineas/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:28
#
---
PstoLineas:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDPsto
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDPsto
  controller: ErpPstoLineas
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: PstoLineas
  id_video: pstolineas
  url_video: null
  feature_list: YES
  conection: ''
  entity: PstoLineas
  table: ErpPstoLineas
  primarykey: IDLinea
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'IDLinea a-z'
      criteria: 'IDLinea ASC'
    -
      title: 'IDLinea z-a'
      criteria: 'IDLinea DESC'
  search_default: IDLinea
  referenced_entities:
    - PstoCab
    - Articulos
    - Almacenes
    - TiposVenta
    - ValoresSN
    - Agentes
    - Promociones
    - EstadosLineasPresupuestos
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDLinea:
      title: IDLinea
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDPsto:
      title: IDPsto
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDPsto, entity: ErpPstoCab, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDArticulo:
      title: Artículo
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 2, caption: IDArticulo, entity: ErpArticulos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Descripcion:
      title: Descripción
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Unidades:
      title: Unidades
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Precio:
      title: Precio
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Descuento:
      title: Dcto
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Importe:
      title: Importe
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    ImporteCosto:
      title: Importe Costo
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    IDAlmacen:
      title: Almacén
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 3, caption: IDAlmacen, entity: ErpAlmacenes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Iva:
      title: Iva
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Recargo:
      title: Recargo
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    ComisionAgente:
      title: Comision Agente
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    ComisionMontador:
      title: Comision Montador
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    IDVenta:
      title: Tipo Venta
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '1'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 4, caption: IDVenta, entity: ErpTiposVenta, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Comisionar:
      title: Comisionar
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 5, caption: Comisionar, entity: ValoresSN, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    IDAgente:
      title: Agente
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 6, caption: IDAgente, entity: ErpAgentes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDComercial:
      title: Comercial
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 7, caption: IDComercial, entity: ErpAgentes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDPromocion:
      title: Promoción
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 8, caption: IDPromocion, entity: ErpPromociones, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    IDEstado:
      title: Estado
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 9, caption: IDEstado, entity: EstadosLineasPresupuestos, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    IDEstado:
      title: Estado
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 9, caption: IDEstado, entity: EstadosLineasAlbaranes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: tinyint, length: '1', min: null, max: null, message: 'Valor Requerido' }
    AltoAl:
      title: Alto Albarán
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    AnchoAl:
      title: Ancho Albarán
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    MtsAl:
      title: Mts Albarán
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    AltoFa:
      title: Alto Factura
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    AnchoFa:
      title: Ancho Factura
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    MtsFa:
      title: Mts Factura
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.000'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
      
