# Module: HistoricoLog
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
HistoricoLog:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Log
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Log
  table: log
  primarykey: IDEvento
  records_per_page: 10
  order_by: IDEvento
  search_default: IDEvento
  columns:
    - 
      title: IDEvento
      field: IDEvento
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: Ip
      field: Ip
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 15
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Fecha
      field: Fecha
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00 00:00:00
      validator:
        nullable: NO
        type: datetime
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: IDAgente
      field: IDAgente
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Evento
      field: Evento
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: null
        min: null
        max: null
        message: Valor Requerido
