# Module: Familias
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Familias:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Familias
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Familias
  table: familias
  primarykey: IDFamilia
  records_per_page: 10
  order_by:
    -
      title: Familia a-z
      criteria: Familia ASC
    -
      title: Familia z-a
      criteria: Familia DESC
  search_default: Familia
  columns:
    -
      title: IDFamilia
      field: IDFamilia
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    -
      title: Familia
      field: Familia
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: Inventario
      field: Inventario
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 1
      validator:
        nullable: NO
        type: integer
        length: 2
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 1
        caption: Con Inventario
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
    -
      title: Trazabilidad
      field: Trazabilidad
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 2
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 2
        caption: Con Trazabilidad
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
    -
      title: Margen Mínimo
      field: MargenMinimo
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: Publicar en Web
      field: PublicarWeb
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 2
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 3
        caption: Publicar en Web
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
    -
      title: Margen Web
      field: MargenWeb
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: Caducidad
      field: Caducidad
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    -
      title: Gestión Tallas/Colores
      field: ConTallasColores
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 2
        min: null
        max: null
        message: Valor Requerido
      aditional_filter:
        order: 3
        caption: Tallas/Colores
        entity: ValoresSN
        method: fetchAll
        params: Descripcion
        type: select
